@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "e:ExportCommand" as ExportCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("export")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("export")
activate AddressBookParser

create ExportCommand
AddressBookParser -> ExportCommand
activate ExportCommand

ExportCommand --> AddressBookParser
deactivate ExportCommand

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> ExportCommand : execute(m)
activate ExportCommand

ExportCommand -> Model : getFilteredCatList()
activate Model

Model --> ExportCommand : cats
deactivate Model

note right of ExportCommand
  Builds HTML string for each cat,
  then writes to export.html
end note

create CommandResult
ExportCommand -> CommandResult
activate CommandResult

CommandResult --> ExportCommand
deactivate CommandResult

ExportCommand --> LogicManager : r
deactivate ExportCommand

[<-- LogicManager
deactivate LogicManager
@enduml
