@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class SplashScreen
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class CatListPanel
Class CatSidebarCard
Class CatDetailPanel
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager ..> SplashScreen
UiManager -down-> "1" MainWindow
MainWindow ..> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" CatListPanel
MainWindow *-down-> "1" CatDetailPanel
MainWindow ..> "1" StatusBarFooter
MainWindow *-down-> "0..1" HelpWindow

CatListPanel -down-> "*" CatSidebarCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
CatListPanel --|> UiPart
CatSidebarCard --|> UiPart
CatDetailPanel --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

CatSidebarCard ..> Model
CatDetailPanel ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

CatListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
