@startuml
!include style.puml
skinparam ArrowFontStyle plain

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> MainWindow : executeCommand("undo")
activate MainWindow

MainWindow -> LogicManager : parseCommand("undo")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("undo")
activate AddressBookParser

create UndoCommand
AddressBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> AddressBookParser
deactivate UndoCommand

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager --> MainWindow : u
deactivate LogicManager

MainWindow -> LogicManager : canUndo()
activate LogicManager

LogicManager -> Model : canUndo()
activate Model

Model --> LogicManager : true
deactivate Model

LogicManager --> MainWindow : true
deactivate LogicManager

MainWindow -> MainWindow : showUndoConfirmationDialog()
activate MainWindow
MainWindow --> MainWindow : confirmed
deactivate MainWindow

opt user confirms

    MainWindow -> LogicManager : executeCommand(u)
    activate LogicManager

    LogicManager -> UndoCommand : execute(m)
    activate UndoCommand

    UndoCommand -> Model : undoLastChange()
    activate Model

    Model --> UndoCommand
    deactivate Model

    UndoCommand --> LogicManager : result
    deactivate UndoCommand
    UndoCommand -[hidden]-> LogicManager : result
    destroy UndoCommand

    LogicManager --> MainWindow : result
    deactivate LogicManager

end

[<-- MainWindow
deactivate MainWindow
@enduml
